---
- name: Calculate current checksum for {{ parent_role }}
  command:
    argv: "{{ ['caketop-checksum', '-', parent_role_path] + cache_paths + artifacts }}"
    stdin: "{{ cache_variables | to_yaml }}"
  register: caketop_checksum

- name: Remember checksum for {{ parent_role }}
  set_fact:
    "{{ checksum_var }}": "{{ caketop_checksum.stdout | trim }}"
