---
- include_tasks: calculate_checksum.yml

- name: Persist checksum for {{ cache_key }}
  copy:
    dest: "{{ checksum_path }}"
    content: "{{ lookup('vars', checksum_var) }}"

- name: Mark {{ cache_key }} as done but not cached
  set_fact:
    "{{ cached_var }}": false
    "{{ done_var }}": true
