---
- include_tasks: calculate_checksum.yml

- name: Persist checksum for {{ parent_role }}
  copy:
    dest: "{{ checksum_path }}"
    content: "{{ lookup('vars', checksum_var) }}"

- name: Mark {{ parent_role }} as done but not cached
  set_fact:
    "{{ cached_var }}": false
    "{{ done_var }}": true
