---
disk_image_name: "{{ lookup('env', 'DISK_IMAGE_NAME') | default(product_slug + '.img', true) }}"
disk_image_size: "{{ lookup('env', 'DISK_IMAGE_SIZE') | default('4G', true) }}"
disk_image_partition_table: "{{ lookup('env', 'DISK_IMAGE_PARTITION_TABLE') | default('gpt', true) }}"
