---
parent_role: "{{ ansible_parent_role_names[0] }}"
cache_key: "{{ lookup('vars', parent_role + '_cache_key', default=parent_role) }}"
parent_role_path: "{{ ansible_parent_role_paths[0] }}"
artifacts: "{{ lookup('vars', parent_role + '_artifacts', default=[build_root + '/' + cache_key]) }}"
checksum_path: "{{ build_root }}/{{ cache_key }}.checksum"
checksum_var: "{{ parent_role }}_checksum"
cached_var: "{{ parent_role }}_cached"
done_var: "{{ parent_role }}_done"
cache_variables: "{{ lookup('vars', parent_role + '_cache_variables', default=[]) }}"
cache_paths: "{{ lookup('vars', parent_role + '_cache_paths', default=[]) }}"
cache_dependencies: "{{ lookup('vars', parent_role + '_cache_dependencies', default=[]) }}"
clean_env: "CLEAN_{{ parent_role | upper }}"
clean_all: "{{ lookup('env', 'CLEAN_ALL') | default(false, true) | bool }}"
force_clean: "{{ lookup('env', clean_env) | default(clean_all, true) | bool }}"
