version: "3.7"

services:
  builder:
    hostname: ${BUILDER_HOSTNAME:-caketop-builder}
    image: ${BUILDER_IMAGE:-caketop/caketop-builder}
    build:
      context: ./builder
      args:
        BUILDER_BASE_IMAGE: ${BUILDER_BASE_IMAGE:-debian:buster-slim}
    volumes:
      - acng:/var/cache/apt-cacher-ng
      - cache:/mnt/cache
      - vartmp:/var/tmp
      - .:/mnt/workdir
      - ./builder/ansible:/usr/lib/caketop-builder/ansible

volumes:
  acng:
  cache:
  vartmp:
