---
- hosts: localhost
  any_errors_fatal: true
  gather_facts: false
  vars:
    builder: "{{ lookup('env', 'BUILDER') | default('disk_image', true) }}"
  tasks:
    - import_role:
        name: "{{ builder }}"
