---
- import_role:
    name: builder_cache
  vars:
    cache_action: validate

- block:
  - name: Create {{ disk_image_name }}
    command:
      argv:
        - truncate
        - --size={{ disk_image_size }}
        - "{{ build_root }}/{{ disk_image_name }}"

  - include_tasks: "{{ disk_image_layout }}_layout.yml"

  - import_role:
      name: builder_cache
    vars:
      cache_action: update
  when: not disk_image_cached
