---
- include_role:
    name: builder_cache
    apply:
      vars:
        cache_action: "{{ 'validate' if debootstrap_cached else 'invalidate' }}"

- block:
  - include_role:
      name: start_acng
    when: not (acng_started | default(false))

  - command: cp -a /mnt/cache/debootstrap /mnt/cache/rootfs

  - import_role:
      name: "{{ os_role }}"
    vars:
      proxy_env: "{{ proxy_env }}"
    delegate_to: rootfs

  - include_role:
      name: builder_cache
      apply:
        vars:
          cache_action: update
  when: not rootfs_cached
