---
- import_role:
    name: builder_cache
  vars:
    cache_action: validate

- block:
  - command:
      argv:
        - mksquashfs
        - "{{ build_root }}/rootfs"
        - "{{ build_root }}/squashfs"
        - -comp
        - "{{ squashfs_compression }}"

  - import_role:
      name: builder_cache
    vars:
      cache_action: update
  when: not squashfs_cached
