---
- import_role:
    name: builder_cache
  vars:
    cache_action: validate

- block:
  - include_role:
      name: start_acng
    when: not (acng_done | default(false))

  - name: Copy debootstrap
    command: cp -a {{ build_root }}/debootstrap {{ build_root }}/rootfs

  - name: Create apt proxy configuration
    copy:
      dest: "{{ build_root }}/rootfs/etc/apt/apt.conf.d/99-caketop.conf"
      content: Acquire::http::Proxy "{{ proxy_env.http_proxy }}";
    when: acng_started

  - import_role:
      name: "{{ os_role }}"
    vars:
      proxy_env: "{{ proxy_env }}"
      os_architecture: "{{ os_architecture }}"
    delegate_to: rootfs

  - name: Remove apt proxy configuration
    file:
      path: "{{ build_root }}/rootfs/etc/apt/apt.conf.d/99-caketop.conf"
      state: absent
    when: acng_started

  - import_role:
      name: builder_cache
    vars:
      cache_action: update
  when: not rootfs_cached
