---
- block:

  - file:
      state: absent
      path: /mnt/cache/system.done

  when: clean_system

- block:

  - file:
      state: absent
      path: /mnt/cache/system

  - command: cp -a /mnt/cache/debootstrap /mnt/cache/system

  - import_role:
      name: "{{ os_role }}"
    vars:
      proxy_env: "{{ proxy_env }}"
    delegate_to: system

  - file:
      state: touch
      path: /mnt/cache/system.done

  when: "'/mnt/cache/system.done' is not exists"
