---
- name: Calculate current checksum for {{ cache_key }}
  command:
    argv:
      - caketop-checksum
      - "-"
      - "{{ parent_role_path }}"
      - "{{ artifact_path }}"
    stdin: "{{ cache_variables }}"
  register: calculated_checksum

- name: Remember checksum for {{ cache_key }}
  set_fact:
    "{{ checksum_var }}": "{{ calculated_checksum.stdout | trim }}"
