---
- include_tasks: invalidate_cache.yml
  when: force_clean or (not dependencies_cached) or (artifact_path is not exists) or (checksum_path is not exists)

- name: Validate checksum for {{ cache_key }}
  block:
    - name: Load cached checksum for {{ cache_key }}
      slurp:
        src: "{{ checksum_path }}"
      register: cached_checksum
    - include_tasks: calculate_checksum.yml
    - name: Invalidate cache for {{ cache_key }}
      include_tasks: invalidate_cache.yml
      when: (cached_checksum['content'] | b64decode | trim) != lookup('vars', checksum_var)
  when: checksum_path is exists
