---
- block:

    - name: Create /mnt/cache/apt-cacher-ng
      file:
        path: /mnt/cache/apt-cacher-ng
        state: directory
        mode: '0755'
        owner: apt-cacher-ng
        group: apt-cacher-ng

    - name: Start apt-cacher-ng
      command:
        cmd: apt-cacher-ng -c /etc/apt-cacher-ng
        creates: /run/apt-cacher-ng/socket

    - name: Set proxy environment
      set_fact:
        proxy_env:
            http_proxy: http://localhost:3142

  when: use_acng

- set_fact:
    acng_started: true
